Web/Controllers/PermanentEmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using PayCalc.ClassLibrary.Models;
using PayCalc.ClassLibrary.Repos;
using PayCalc.ClassLibrary.Services;
using Web.Models;

namespace Web.Controllers
{
    public class PermanentEmployeeController : Controller
    {
        private readonly IEmployeeRepository<PermanentEmployee> _permRepo;
        PermanentEmployeeTaxCalculator permCalc = new PermanentEmployeeTaxCalculator();
        DateCalculator dateCalculations = new DateCalculator();
        public PermanentEmployeeController(IEmployeeRepository<PermanentEmployee> permRepo)
        {
            _permRepo = permRepo;
        }

        public IActionResult EmployeeList()
        {
            PermanentEmployeeViewModel permView = new PermanentEmployeeViewModel(_permRepo.ReadAll());
            return View(permView);
        }

        public IActionResult AddEmployee()
        {
            return View();
        }

        public IActionResult EmployeeListDeleteConfirmed()
        {
            PermanentEmployeeViewModel permView = new PermanentEmployeeViewModel(_permRepo.ReadAll());
            return View(permView);
        }

        [HttpPost]
        public IActionResult AddEmployee(PermanentEmployee inputEmployee)
        {
            _permRepo.Create(inputEmployee.StartDate, inputEmployee.FirstName, inputEmployee.LastName, inputEmployee.Salary, inputEmployee.Bonus, null, null);
            return RedirectToAction("EmployeeList");
        }

        public IActionResult DeleteEmployee(int id)
        {
            if (_permRepo.Delete(id) == true)
            {
                return RedirectToAction("EmployeeListDeleteConfirmed");
            }
            return RedirectToAction("InvalidID", "Error");
        }

        public IActionResult UpdateEmployee(int id)
        {
            List<PermanentEmployee> employees = new List<PermanentEmployee>(_permRepo.ReadAll());
            if (employees.Exists(x => x.ID == id) == true)
            {
                PermanentEmployee employee = _permRepo.Read(id);
                return View(employee);
            }
            else
            {
                return RedirectToAction("InvalidID", "Error");
            }
        }

        [HttpPost]
        public IActionResult UpdateEmployee(PermanentEmployee updateEmployee)
        {
            _permRepo.Update(updateEmployee.ID, updateEmployee.FirstName, updateEmployee.LastName, updateEmployee.Salary, updateEmployee.Bonus, null, null);
            return RedirectToAction("EmployeeList");
        }

        public IActionResult ReadEmployee(int id)
        {
            List<PermanentEmployee> employees = new List<PermanentEmployee>(_permRepo.ReadAll());
            if (employees.Exists(x => x.ID == id) == true)
            {
                PermanentEmployee? employee = _permRepo.Read(id);
                int amountOfWeeksWorkedByEmployee = dateCalculations.WeeksWorkedSinceStartDate(employee, DateTime.Today);
                PermanentEmployeeSalary? empWSal = new PermanentEmployeeSalary { ID = employee.ID, FirstName = employee.FirstName, LastName = employee.LastName, Salary = employee.Salary, Bonus = employee.Bonus, SalaryAfterTax = employee.Salary - permCalc.TotalTaxPaid(employee), StartDate = employee.StartDate };
                DetailedPermanentEmployeeViewModel viewModel = new DetailedPermanentEmployeeViewModel(empWSal, amountOfWeeksWorkedByEmployee);
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("InvalidID", "Error");
            }

        }
    }
}

Web/Controllers/TemporaryEmployeeController.cs
using Microsoft.AspNetCore.Mvc;
using PayCalc.ClassLibrary.Models;
using PayCalc.ClassLibrary.Repos;
using PayCalc.ClassLibrary.Services;
using Web.Models;

namespace Web.Controllers
{
    public class TemporaryEmployeeController : Controller
    {
        private readonly IEmployeeRepository<TemporaryEmployee> _temporaryRepo;
        TemporaryEmployeeTaxCaculator tempCalc = new TemporaryEmployeeTaxCaculator();
        DateCalculator dateCalculations = new DateCalculator();

        public TemporaryEmployeeController(IEmployeeRepository<TemporaryEmployee> tempRepo)
        {
            _temporaryRepo = tempRepo;
        }

        public IActionResult EmployeeList()
        {
            TemporaryEmployeeViewModel tempView = new TemporaryEmployeeViewModel(_temporaryRepo.ReadAll());
            return View(tempView);
        }
        public IActionResult AddEmployee()
        {
            return View();
        }

        public IActionResult EmployeeListDeleteConfirmed()
        {
            TemporaryEmployeeViewModel tempView = new TemporaryEmployeeViewModel(_temporaryRepo.ReadAll());
            return View(tempView);
        }

        [HttpPost]
        public IActionResult AddEmployee(TemporaryEmployee inputEmployee)
        {
            _temporaryRepo.Create(inputEmployee.StartDate, inputEmployee.FirstName, inputEmployee.LastName, null, null, inputEmployee.DayRate, inputEmployee.WeeksWorked);
            return RedirectToAction("EmployeeList");
        }

        public IActionResult DeleteEmployee(int id)
        {
            if (_temporaryRepo.Delete(id) == true)
            {

                return RedirectToAction("EmployeeListDeleteConfirmed");
            }
            return RedirectToAction("InvalidID", "Error");
        }

        public IActionResult UpdateEmployee(int id)
        {
            List<TemporaryEmployee> employees = new List<TemporaryEmployee>(_temporaryRepo.ReadAll());
            if (employees.Exists(x => x.ID == id) == true)
            {
                return View(_temporaryRepo.Read(id));
            }
            else
            {
                return RedirectToAction("InvalidID", "Error");
            }
        }

        [HttpPost]
        public IActionResult UpdateEmployee(TemporaryEmployee updateEmployee)
        {
            _temporaryRepo.Update(updateEmployee.ID, updateEmployee.FirstName, updateEmployee.LastName, null, null, updateEmployee.DayRate, updateEmployee.WeeksWorked);
            return RedirectToAction("EmployeeList");
        }
        public IActionResult ReadEmployee(int id)
        {
            List<TemporaryEmployee> employees = new List<TemporaryEmployee>(_temporaryRepo.ReadAll());
            if (employees.Exists(x => x.ID == id) == true)
            {
                TemporaryEmployee? employee = _temporaryRepo.Read(id);
                int amountOfWeeksWorkedByEmployee = dateCalculations.WeeksWorkedSinceStartDate(employee, DateTime.Today);
                TemporaryEmployeeSalary? empWSal = new TemporaryEmployeeSalary { StartDate = employee.StartDate, ID = employee.ID, FirstName = employee.FirstName, LastName = employee.LastName, DayRate = employee.DayRate, WeeksWorked = employee.WeeksWorked, SalaryAfterTax = (employee.DayRate * (5 * employee.WeeksWorked)) - tempCalc.TotalTaxPaid(employee) };
                DetailedTemporaryEmployeeViewModel viewModel = new DetailedTemporaryEmployeeViewModel(empWSal, amountOfWeeksWorkedByEmployee);
                return View(viewModel);
            }
            else
            {
                return RedirectToAction("InvalidID", "Error");
            }
        }
    }
}

Web/Views/Shared/InvalidID.cshtml
<h1 class="text-danger">Error.</h1>
<h2 class="text-danger">An error occurred while processing your request.</h2>

<h3>Invalid ID.</h3>

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Employee Database</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Employee Database</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class ="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PermanentEmployee" asp-action="EmployeeList">Permanent Employees</a>
                        </li>
                        <li class ="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TemporaryEmployee" asp-action="EmployeeList">Temporary Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>